name: Codespace Startup

on:
  codespaces:
    opened

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Send welcome message
        run: |
          echo "## 🚀 Nova Proxy is ready to run!" >> $GITHUB_STEP
